//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanysSystem.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string PageDescription { get; set; }
        public string PageURL { get; set; }
        public string PageIcon { get; set; }
        public bool isEnabled { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
