//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcanysSystem.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineDrive
    {
        public int Id { get; set; }
        public string FileNameGUID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime UploadedOn { get; set; }
        public int UploadedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
